### ISSUE TITLE
Getting an error after installing via Cocoapods.

### ISSUE THREAD

**Issue by euroboy** [urbanairship/ios-library#156] opened 2017-10-31 08:04 UTC
I added `pod 'UrbanAirship-iOS-SDK', '~> 8.6'`  to my podfile, and after installing pods I'm getting the following error on build:

`error: Resource "/Users/me/Library/Developer/Xcode/DerivedData/MyProject/Build/Products/Debug-iphoneos/UrbanAirship-iOS-SDK/AirshipResources.bundle" not found. Run 'pod install' to update the copy resources script.`

I tried to delete pods caches, but with no luck. Cocoapods version: 1.3.1. Any ideas how to solve it?

**Comment by rlepinski** [comment] 2017-11-01 01:29
@euroboy I am unable to reproduce the issue. Could you share a sample project that reproduces the issue? Thanks

**Comment by euroboy** [comment] 2017-11-01 07:33
@rlepinski Here is a sample project. Try to build for simulator.
[Sample.zip](https://github.com/urbanairship/ios-library/files/1433401/Sample.zip)

**Comment by BrianBatchelder** [comment] 2017-11-01 20:00
@euroboy Your sample project is a static library. Is that what you intended?

**Comment by euroboy** [comment] 2017-11-02 07:28
@BrianBatchelder Yes.

**Comment by BrianBatchelder** [comment] 2017-11-02 17:20
@euroboy Are you sure you want to build a static library that includes our SDK? A more common pattern is to have two static libraries, or a static library and a framework.

**Comment by euroboy** [comment] 2017-11-06 14:15
@BrianBatchelder Yes, this is exactly what I want to achieve, but I'm still unable to do that.

**Comment by BrianBatchelder** [comment] 2017-11-06 17:37
@euroboy - I'm going to close this for now. Please let us know if you have further issues.

**Comment by BrianBatchelder** [comment] 2017-11-07 01:09
@euroboy We don't support building our SDK inside of another static library. You might be able to merge our pre-built static library. You can find it at: https://bintray.com/urbanairship/iOS/urbanairship-sdk .

**Closed by BrianBatchelder** 2017-11-07 01:09 UTC
