### ISSUE TITLE
Deployment target raised to 10.0 for AppExtensions pod despite no code changes

### ISSUE THREAD

**Issue by robinkunde** [urbanairship/ios-library#165] opened 2018-02-05 21:01 UTC
This change prevents me from integrating it via cocoapods in an app with deployment target 9.0 without some manual workarounds.

AppExtensions uses Apple's UserNotifications framework, which requires iOS 10.0. When the deployment target on the AppExtensions pod was iOS 9.0 before, Xcode would automatically link UserNotifications as an optional framework, and since the extension is never called on iOS 9.0, this caused no problems.
However, if the deployment target on the pod is 10.0, Xcode will instead link UserNotifications as a required framework. The app will still build (this is a bug in Xcode, IMO), but it will now crash at runtime on iOS 9.0. If I manually link UserNotifications as optional, it will work like before.

Since there were no code changes to the extension itself, I was wondering if this change was intentional.

**Comment by rlepinski** [comment] 2018-02-05 22:13
Not intentional. Ill look into right now. Looks like it was done to fix some of the new lint checks in the cocoapods version. Thanks for reporting this issue, we should have a fix shortly.

**Comment by rlepinski** [comment] 2018-02-05 23:26
@robinkunde Trying to get a better understanding of this issues so we hopefully prevent this regression in the future. Whats your deployment targets for your main app and extension? Pod version? Pod platform for each?  And are you installing the extension in both the main app and the extension target or just the extension?  Thanks

**Comment by robinkunde** [comment] 2018-02-06 00:03
@rlepinski 
Deployment targets:
App 9.0
NotificationServiceExtension 10.0

Cocoapods 1.4.0
Platform 9.0 for all
NotificationServiceExtension target is the only one that gets the pod

(I tried setting the platform to 10.0 just for the extension target so I could install v9.0 of the AppExtensions pod, which led to the problems described)
(There's a bug in Cocoapods where pods only added to an extension are also added to the app target. However, I removed it by hand and it didn't affect my issue).

**Comment by rlepinski** [comment] 2018-02-07 01:04
Should be fixed in 9.0.1. We left the deployment target to 10 as it helps prevent people deploying the extension to iOS 9 and having a similar failure. The framework is marked as weak now in the pod spec.

**Closed by rlepinski** 2018-02-07 01:04 UTC
