### ISSUE TITLE
Devices not receiving push notifications anymore after restoration from iCloud backup

### ISSUE THREAD

**Issue by defagos** [urbanairship/ios-library#313] opened 2022-03-08 14:39 UTC
# Preliminary Info

### What Airship dependencies are you using?

16.4.0

### What are the versions of any relevant development tools you are using?

Xcode 13.2.1

# Report

### What unexpected behavior are you seeing?

Among devices related to the same iCloud backup, only one device can receive push notifications.

### What is the expected behavior?

Restoring devices from an iCloud backup does not prevent other devices related to the same backup from receiving push notifications.

### What are the steps to reproduce the unexpected behavior?

1. Install some app using Airship for push notifications and check that push notifications are working well.
2. Backup the device on iCloud.
3. Erase and restore another device from the same iCloud backup.
4. Only one device is now able to receive push notifications. The other device cannot receive them anymore.

### Do you have logging for the issue?

No

### What happens

To cope with the fact that device tokens might be refreshed over time Airship introduces the concept of a [channel identifier](https://support.airship.com/hc/en-us/articles/213492363-Device-Identifiers-for-iOS) for which a relationship to a valid device token is maintained server-side. The mapping for some channel identifier can easily be retrieved using Airship API (https://go.urbanairship.com/api/channels/[channel_id]).

Channel identifiers are [persisted](https://github.com/urbanairship/ios-library/blob/16.4.0/Airship%2FAirshipCore%2FSource%2FChannelRegistrar.swift#L68-L76) on device in a plist stored in the `Library` app folder and the plist itself is included in iCloud backups. After a device has been restored from an iCloud backup several devices might therefore end up sharing the same channel identifier from the same plist. Since only a single device token can be associated with a channel identifier only one device ultimately receives push notifications.

### Workaround

The only known workaround at the moment is to reinstall the app on a device not receiving push notifications. This forces a new channel identifier to be created, ensuring that the device token can be reliably associated with it.

### Possible solutions

It is possible to [exclude](https://developer.apple.com/documentation/foundation/urlresourcevalues/1780002-isexcludedfrombackup) files from an iCloud backup. Maybe some Airship device-related settings should be stored in a separate plist excluded from iCloud backup.

**Comment by rlepinski** [comment] 2022-03-09 00:07
We have a mechanism that clears the channel id if we detect an app restore. Its using a pretty round about way of checking by storing something in the keychain. Did you reproduce this issue and verify they all have the same channel ID?

**Comment by defagos** [comment] 2022-03-09 06:28
Thank you very much for your feedback.

I could reproduce the issue with a pair of devices and a common Apple ID, as outlined above. We have a helpful feature in our app which allows us to dump a few interesting things about the app environment, among them the device token and the channel ID. Using this feature I could verify that the two devices had different tokens but a common channel ID.

The keychain might be synchronized between devices linked with a common Apple ID, so I suppose relying on the keychain to identify different installations might provide an explanation? Or am I maybe missing something?

**Comment by rlepinski** [comment] 2022-03-09 17:12
We set the attribute to store the value only on this device. We will take a look, thank you for reproducing!

**Comment by defagos** [comment] 2022-03-10 06:06
Thank you very much! Just let me know if you need help or more information.

**Comment by defagos** [comment] 2022-04-01 14:23
I saw that you released the fix in version [16.5.0](https://github.com/urbanairship/ios-library/releases/tag/16.5.0), thank you very much!

**Comment by rlepinski** [comment] 2022-04-01 15:18
@defagos I was going to verify the fix in a live app today before I notified you. This issue is a pain to reproduce.

**Comment by rlepinski** [comment] 2022-04-01 21:43
@defagos Looks like it still recreates for us but I believe it has to do with the message center module. Ill try to get a path next week out.

**Comment by rlepinski** [comment] 2022-04-04 03:35
@defagos Ill have a patch going out tomorrow. I verified the fix should generate a new channel by using xcode to download container and restore it on a different device. I made sure it had the old channel in the shared preferences, detected a restore, and recreated a new channel. If you restore on the same device it will recover the same channel.

16.5.0 has a crash, so please wait for 16.5.1. Sorry for the long wait.

**Comment by defagos** [comment] 2022-04-04 05:05
@rlepinski Thank you very much for your work on this issue. Take the time you need, no worries. Let me know if you need me to test anything before you release the 16.5.1 update.

**Comment by rlepinski** [comment] 2022-04-04 17:50
Was able to get 16.5.1 out today. Going to close this as fixed. 

When testing, make sure you restore on a different device. We found that restoring on the same device even after the device is reset still recovers the same channel. We use `kSecAttrAccessibleAfterFirstUnlockThisDeviceOnly` when storing keys in the keychain app restore detection.

**Closed by rlepinski** 2022-04-04 17:50 UTC

**Comment by defagos** [comment] 2022-04-04 18:10
Thank you very much for the fix, I will test it tomorrow.

**Comment by defagos** [comment] 2022-04-07 06:44
I confirm the issue has been fixed, thank you very much for all the work you have done.

An important detail, though, which I assume is related to your [comment above](https://github.com/urbanairship/ios-library/issues/313#issuecomment-1087842875): For the fix to work an app using Airship must first be updated to a version embedding Airship 16.5.1+ and run once before the device is backed up. This way keychain attributes will be correct in the backup and restoration from this backup on another device will ensure a new channel ID is produced.

**Comment by rlepinski** [comment] 2022-04-07 16:23
@defagos We were setting the attributes properly on the keys, but the device token was also cached and used for the channel creation. Our backend will match on device token and return the same channel back. The fix was to clear that cached token when we detect a restore. I believe this will be fixed as long as the restored app version is using 16.5.1.
