### ISSUE TITLE
Extremely long build times with Carthage

### ISSUE THREAD

**Issue by glaures-ioki** [urbanairship/ios-library#334] opened 2022-08-09 13:48 UTC
# Preliminary Info

### What are the versions of any relevant development tools you are using?
Airship 16.7.0, 16.9.1
Carthage 0.38.0
Xcode 13.4.1

# Report

### What unexpected behavior are you seeing?

With the update to the latest version, to be ready for Xcode 14, we encountered extremely long build times which prevent us from using this version.
Both tests were done on the same machine, Mac Book pro with M1 pro (10 cores and 32GB of RAM)
With version 16.7.0, total build time of about 20 mins
With version 16.9.1, total build time is more than 1h 30mins

Since our CI has a limited build time, we cannot build our app anymore since it's timing out during the first build (when no cache is present):
```
*** Building scheme "AirshipNotificationServiceExtension" in Airship.xcworkspace
*** Building scheme "AirshipNotificationContentExtension" in Airship.xcworkspace
*** Building scheme "AirshipAutomation" in Airship.xcworkspace
*** Building scheme "AirshipAccengage" in Airship.xcworkspace
*** Building scheme "AirshipBasement" in Airship.xcworkspace
*** Building scheme "AirshipChat" in Airship.xcworkspace
*** Building scheme "AirshipCore" in Airship.xcworkspace
timeout after 5400 seconds
```
For example, if I take `AirshipAccengage`, the build time seems to be 3 to 4 times longer with the latest version.
### What is the expected behavior?
Version 16.9.1 should have a similar build time as version 16.7.0.

### What are the steps to reproduce the unexpected behavior?
Create a new project and use Carthage to import the latest version of Airship.

**Comment by rlepinski** [comment] 2022-08-09 15:57
Thanks for the report, we will see if we can figure out what caused it. We can also look into bringing back prebuilt frameworks for carthage. If i get those uploaded today could you run a quick test to see if it resolves it for you?

**Comment by glaures-ioki** [comment] 2022-08-09 16:06
Thank you for the quick reply, yes prebuilt xcframeworks could work too. 
Of course, no problem to test it, just give me a heads up when it's ready.

**Comment by rlepinski** [comment] 2022-08-09 16:30
We already provide prebuilt xcframeworks but its not uploaded in a way carthage expects. Doing the long build right now using carthage so I can compare any differences and will upload it. 

I have no idea what changed that would cause the long builds but I have someone looking into it.

**Comment by rlepinski** [comment] 2022-08-09 20:49
Struggling to get the carthage build working on my machine, i think the xcode betas have messed up my tvos simulators. 

It seems that the explosion of build times is due to adding a shared schema called `AirshipRelease` that we added to reduce the build time for our xcframeworks. Does not look like carthage has a way of excluding them from either the client or the framework so we will have to look into other solutions.

**Comment by rlepinski** [comment] 2022-08-15 16:31
Still working on this. Airships slow build times is due to being multi module. Each module needs Core and Basement and when you build it for achieving it basically has to do rebuild those modules over and over again. I added a new target to build all the frameworks at the same time for our internal builds, but that is being picked up by Carthage. Xcode has an aggregate target that I should have used before, I believe carthage will ignore those since it doesnt have any real output. I am working on moving to using that type of target for our internal builds and then once done I will be able to provide xcframeworks for the normal modules.  Hoping to get this done today but testing it takes forever

**Comment by rlepinski** [comment] 2022-08-16 16:48
@glaures-ioki I updated the release and provided a binary of xcframeworks

Seems to be working for me:
```
 carthage bootstrap --use-xcframeworks
*** No Cartfile.resolved found, updating dependencies
*** Cloning ios-library
*** Checking out ios-library at "16.9.2"
*** xcodebuild output can be found in /var/folders/kp/lst8wn4j3bv_j6n572r32zc00000gp/T/carthage-xcodebuild.3BpIbx.log
*** Downloading ios-library binary at "16.9.2"
```

Please let me know if you run into any issues.

**Closed by rlepinski** 2022-08-16 16:48 UTC

**Comment by stherold** [comment] 2022-10-19 19:25
Hey there,

I replace my collegue and will continue looking into this. The problem is that we use Tuist to generate our very big/complex project and this tool has currently no means of specifying the xcframeworks flag for Carthage which means it builds all dependencies from scratch. 

Therefore my only solution for now was to download your binaries manually. Of cource this is not a nice solution. You yourself wrote that testing takes forever. Can you think of a solution which solved the long build time problem for you and for us? For example Xcode uses incremental builds so why does it need to rebuild the common dependencies over and over? What comes to my mind is to setup the core dependencies in different repos and declare them as e.g. carthage dependencies in the other libraries so they have to be built only once.

What do you think?

**Comment by rlepinski** [comment] 2022-10-19 20:48
We are reducing the number of modules and hoping to resolve some of build speed issues in SDK 17. I don't think multiple modules across repos would help, the other modules still need a reference to core in order to build properly so not sure if that would actually help at all. Not to mention the complexity we would have to manage in order to keep everything in sync. 

When we generate xcframeworks I was able to use an aggregate target to take advantage of caching, but Carthage does not support that or the ability to exclude targets. I am hoping to have an alpha SDK 17 out in a few weeks, can we see if that solves some of the build speed problems? 

Another thought would be to integrate with xcframeworks and script your build to pull the binary zip and replace them if you want to update it automatically. 

Also, what CI system are you using? Github actions is very slow compared to how long it takes on my machine, like 3x time difference. Curious if you are on the same thing or if you have some other build provider.

**Comment by stherold** [comment] 2022-10-20 09:08
Ah okay I understand 👍

In our grooming today we came up with a solution that might work very well for you and for us. Let me explain:

Actually Carthage supports binary frameworks from external sources and actually we already use this mechanism for Firebase and Google Maps. They (this is Carthage native and has nothing to do with Tuist) store their versions together with the archived binaries in ZIP archives on one of their servers. These releases are organized in a [JSON key-value file](https://dl.google.com/dl/firebase/ios/carthage/FirebaseAnalyticsBinary.json). In the Cartfile we then specify this JSON file and the version we want and voilá it downloads the binaries. This approach works very well for many years for us. 

My question now is if it would be possible for you to setup such a JSON on one of your servers - it could just be a file in any public Git(Hub) repo. This way we can properly setup binary downloads using Carthage/Tuist. 

![Screen Shot 2022-10-20 at 11 08 05](https://user-images.githubusercontent.com/64915710/196906636-9f5f37a5-87eb-4fcd-83f0-55932cb6d7f2.png)

**Comment by stherold** [comment] 2022-10-20 16:55
Yeah this seems to work too. I will continue to host the JSON file though, because when we would point to the Asset directly in our local Cartfile, we would not be able to leverage Carthages versioning system (e.g. `upToNextMajor` etc.). 

To summarize:
- nobody needs to host the binaries - that's done by GH.
- Hosting/Maintaining the JSON somewhere is handy since it enables Carthages versioning system for users. No user must manually update each minor/patch version when this JSON exists on a server. Is that something you could do? Mine now looks like [this](https://github.com/Blackjacx/airship-carthage-binaries/blob/main/airship/ios/carthage/Airship.json) which has to be extended with each new version.

**Comment by rlepinski** [comment] 2022-10-20 18:05
I should be able to just host it in this repo right? If I build it into our deploy there would be a few hours where the .zip would not be available when the json gets updated. Ill see about other options.

**Comment by rlepinski** [comment] 2022-10-24 18:56
I didnt get this done yet for 16.10 but will try for a follow up patch. My current idea is to just wire up generating the JSON file with our helper update_version script. Going to have two of them at the start, one for Xcode14.1 builds (for live activities) and one for 13.x compatible builds (without live activities). Then in SDK 17 just have a single one.

**Comment by stherold** [comment] 2022-10-25 19:04
That sounds super cool! Thanks a lot :)

**Comment by rlepinski** [comment] 2022-11-02 23:12
@stherold We are going to have a new release that reduces the build time significantly, hopefully out tomorrow. Can we see if that improvement removes the need for prebuilt frameworks?  If not, ill manually host the file and get everything going but ideally we can just have Carthage do its thing.

**Comment by rlepinski** [comment] 2022-11-03 20:24
@stherold New release is out, I did not publish any prebuilt frameworks for Carthage yet. Could you try using 16.10.1 to see if  the build times are reasonable for you?

**Comment by stherold** [comment] 2022-11-07 09:32
Actually we are quite happy with the prebuilt frameworks hosted on GitHub since we need to drastically reduce our build times (CI gets super expensive) and Airship took a big amount of the build time even before the build time issues. 

So we would like to continue to use the prebuilt GitHub assets. They are also available. Jzst the JSON file is missing. Don't get me wrong but that is also a Carthage feature, e.g. Google is using that extensively. It just needs to be hosted somewhere. Right now we still have it in our repo which also works fine.

**Comment by rlepinski** [comment] 2023-09-01 17:02
@stherold Year late, but we are starting to host our own json files
https://github.com/urbanairship/ios-library-prebuilt/blob/main/Carthage/Airship.json
https://github.com/urbanairship/ios-library-prebuilt/blob/xcode-15/Carthage/Airship.json
