### ISSUE TITLE
Compile errors with Xcode 15

### ISSUE THREAD

**Issue by MacMark** [urbanairship/ios-library#364] opened 2023-06-08 10:15 UTC
# Preliminary Info

### What Airship dependencies are you using?
Swift Package https://github.com/urbanairship/ios-library

### What are the versions of any relevant development tools you are using?
Xcode 15

# Report

### What unexpected behavior are you seeing?
When trying to build the existing project with Xcode 15 (which compiles with Xcode 14):

Command SwiftCompile failed with a nonzero exit code

### What is the expected behavior?
Should compile

### What are the steps to reproduce the unexpected behavior?
Try to use and compile AirshipCore with Xcode 15

### Do you have logging for the issue?

See attachment
[Build Radio.de_2023-06-08T12-08-00.txt](https://github.com/urbanairship/ios-library/files/11686813/Build.Radio.de_2023-06-08T12-08-00.txt)

**Comment by Dragna** [comment] 2023-06-08 14:50
same problem with the version 17 of airship which is currently in beta

**Comment by rlepinski** [comment] 2023-06-08 14:59
This is a duplicate of https://github.com/urbanairship/ios-library/issues/362

Pretty sure its this issue - https://github.com/apple/swift/issues/66359

I was able to compile if I set my swift optimization flag to `-O`

**Closed** 2023-06-08 14:59 UTC
