### ISSUE TITLE
"Airship.TaskManager -  Request: UAEventManager.upload"

### ISSUE THREAD

**Issue by WJacobsNL** [urbanairship/ios-library#342] opened 2022-11-02 15:09 UTC
❗For how-to inquiries involving Airship functionality or use cases, please
contact (support)[https://support.airship.com/].

# Preliminary Info

### What Airship dependencies are you using?

16.10.0
### What are the versions of any relevant development tools you are using?

Xcode 14.1
# Report

### What unexpected behavior are you seeing?

Lot's of logging mentioning background tasks after backgrounding the app several times:
"[BackgroundTask] Background Task 3129 ("Airship.TaskManager -  Request: UAEventManager.upload"), was created over 30 seconds ago. In applications running in the background, this creates a risk of termination. Remember to call UIApplication.endBackgroundTask(_:) for your task in a timely manner to avoid this."
### What are the steps to reproduce the unexpected behavior?

I've been backgrounding and foregrounding the app several times within a couple of minutes. This seems to trigger these logs

**Comment by rlepinski** [comment] 2022-11-03 16:52
We use background tasks but always invalidate them when it expires. This is just a warning that we are taking a long time. This warning might happen if the API times out since our requests have a default timeout of 60 seconds. If you enable verbose logging you can probably track our analytics upload requests to see whats taking so long but you should be able to safely ignore this.

**Comment by SwiftNativeDeveloper** [comment] 2023-01-05 18:22
I've also noted seeing this a bunch when debugging my app. I haven't seen any MetricKit task assertion exits but I will continue to watch for them: [MetricKit - Background Task Assertion](https://developer.apple.com/documentation/metrickit/mxbackgroundexitdata/3552272-cumulativebackgroundtaskassertio)

@rlepinski do you have metrics / analytics on how long the network calls typically take? I know it is subject to device and environment conditions but I'm still curious.

**Comment by rlepinski** [comment] 2023-01-05 18:36
@SwiftNativeDeveloper We always invalidate our tasks when expired. The issue is if we create a task in the foreground and a request takes too long (default timeout is 60 seconds?), we wont expire the task til the request finishes. Invalidating before the request finishes then has an issue with the device moving to the background. Only grabbing a background task if the task moves to the background is a possibility but that feels like a needless complication just for a hopefully rare log message.

We have some server metrics on request times, but that wont represent the time from device to server, or when the request times out due to network connection issues.

**Comment by SwiftNativeDeveloper** [comment] 2023-01-05 19:53
@rlepinski yeah I totally agree with the approach as it is Apple's recommendation. That is, ask for a background task even if you are in foreground so when you transition to background you're all set. Maybe this would be better approached with a feedback to apple to reconsider their log message :).

**Comment by rlepinski** [comment] 2023-01-05 21:44
Submitted - FB11924619

**Comment by rlepinski** [comment] 2023-02-23 04:15
Going to close this as its not something I think we should fix. Hopefully Apple addresses the feedback.

**Closed** 2023-02-23 04:15 UTC
