### ISSUE TITLE
Distribute  App not showing 

### ISSUE THREAD

**Issue by ChristianFreny** [urbanairship/ios-library#282] opened 2021-06-10 06:27 UTC
# Preliminary Info

### What Airship dependencies are you using?
Using airship 14.5.0

### What are the versions of any relevant development tools you are using?
Xcode 12.4 and swift package manager
# Report

### What unexpected behavior are you seeing?
After adding airship whenever I archive it's showing me distribute content I am not able to generate ipa of my app

### What is the expected behavior?
it should show distribute app and allow me to generate spa file 

### What are the steps to reproduce the unexpected behavior?
just add airship from Swift package manager and archive app it will not allow to distribute app it will show distribute content and export archive not IPA file 

### Do you have logging for the issue?
NO

**Comment by oristanovic** [comment] 2021-06-11 09:42
@ChristianFreny It seems that the issue is related to the AirshipChat module, we're looking into it. If you're not using this module and need to release your app, you can do so by removing the module before archiving.

**Comment by rlepinski** [comment] 2021-07-02 19:47
Should of been fixed in 14.5.1

**Closed by rlepinski** 2021-07-02 19:47 UTC
