### ISSUE TITLE
Carthage generates extra file

### ISSUE THREAD

**Issue by LucasKovacs** [urbanairship/ios-library#144] opened 2017-07-27 02:56 UTC
I'm having the following issue when submitting to the AppStore:

ERROR ITMS-90171: "Invalid Bundle Structure - The binary file 'MyApp.app/Frameworks/AirshipKit.framework/AirshipResources.bundle/AirshipResources' is not permitted. Your app can’t contain standalone executables or libraries, other than the CFBundleExecutable of supported bundles. Refer to the Bundle Programming Guide at https://developer.apple.com/go/?id=bundle-structure for information on the iOS app bundle structure."

I follow all the steps in the Carthage github site and follow every instruction. The project builds without errors. But this happens when I try to submit to the store or validate the ipa file.

I think that file shouldn't be generated.

I'm using the latest build of course

**Comment by rlepinski** [comment] 2017-07-27 21:33
Looks like an xcdatamodel file had codegen enabled that caused an executable to be generated in the airship resources... Working on a fix.

**Comment by LucasKovacs** [comment] 2017-07-27 22:50
@rlepinski thanks a lot for your reply! I had no idea what else to do. UA support couldn't help me an insisted a lot that I was not following the right steps :/

**Comment by rlepinski** [comment] 2017-07-27 23:10
Fixed in 8.5.1. Please reopen if you are still having that issue.

**Closed** 2017-07-27 23:12 UTC

**Comment by LucasKovacs** [comment] 2017-07-28 01:52
This issue seems to be fixed. Although I'm getting this warning now

ld: warning: ignoring file /Users/user/Library/Developer/Xcode/DerivedData/MyAppName-gqedvcccdeiubvafmoclqbjdqaxp/Build/Products/Debug-iphoneos/AirshipAppExtensions.framework/AirshipAppExtensions, file was built for arm64 which is not the architecture being linked (armv7): /Users/user/Library/Developer/Xcode/DerivedData/MyAppName-gqedvcccdeiubvafmoclqbjdqaxp/Build/Products/Debug-iphoneos/AirshipAppExtensions.framework/AirshipAppExtensions

**Comment by rlepinski** [comment] 2017-07-28 01:56
Update the architectures on your extension to include arm64

**Comment by LucasKovacs** [comment] 2017-07-28 01:59
@rlepinski How can I do that? The library was auto generated by Carthage.

**Comment by rlepinski** [comment] 2017-07-28 02:01
On the extension that is consuming the library. Our lib is built for all the  valid iOS architectures.

**Comment by LucasKovacs** [comment] 2017-07-28 02:10
I have just include the library, there's no extension yet.  Maybe that's why is throwing the warning

**Comment by rlepinski** [comment] 2017-07-28 02:11
You only want to include AirshipKit, not the extension for the main app target. We will update our Carthage docs tomorrow as that are out of date.with the latest Carthage release.

**Comment by LucasKovacs** [comment] 2017-07-28 02:15
Ok I'll remove it then.

One more question

Why I'm getting this issues if I choose an iPhone 4S or iPhone 5 (8.4 or 10.3.1)? Above iPhone 5s works fine, no matter which iOS version is using.

  "_OBJC_CLASS_$_UAConfig", referenced from:
  "_OBJC_CLASS_$_UAirship", referenced from:
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by rlepinski** [comment] 2017-07-28 02:38
Simulator or devices? The lib is iOS 8+ only.

**Comment by LucasKovacs** [comment] 2017-07-28 02:47
Simulators iPhone 4S or iPhone 5 (8.4 or 10.3.1)

**Comment by rlepinski** [comment] 2017-07-28 05:59
What architectures do you have listed for your apps target?

**Comment by rlepinski** [comment] 2017-07-28 17:06
I am unable to reproduce your issue using the same iPhone 4S simulator running i386. Could you run `lipo -info Carthage/Build/iOS/AirshipKit.framework/AirshipKit` to see what architectures carthage built for you.

Here is my output: `Architectures in the fat file: Carthage/Build/iOS/AirshipKit.framework/AirshipKit are: i386 x86_64 armv7 armv7s arm64`

**Comment by LucasKovacs** [comment] 2017-07-28 19:41
@rlepinski this is the result

**First command**
Architectures in the fat file: Carthage/Build/iOS/AirshipKit.framework/AirshipKit are: i386 x86_64 armv7 armv7s arm64 

**Second command**
Xcode 8.3.3
Build version 8E3004b

**Comment by rlepinski** [comment] 2017-07-28 20:10
@LucasKovacs Not sure whats going on here. Looks like everything is working on our end (i386 is included). Maybe wipe your derived data and try again? Might be an issue with Carthage. Do you have any other frameworks through carthage?

**Comment by LucasKovacs** [comment] 2017-07-28 20:58
No UA is the only framework I'm using. How can I clean the derived data?

**Comment by rlepinski** [comment] 2017-07-28 21:01
run `rm -rf ~/Library/Developer/Xcode/DerivedData/`

**Comment by LucasKovacs** [comment] 2017-07-28 21:08
@rlepinski that fixed the issue. Thanks a lot! Can you tell me why clearing that fixed it?

**Comment by rlepinski** [comment] 2017-07-28 21:16
Derived data is xcode cache, build files, other junk. Sometimes you can confuse xcode where it wont update certain cached build files. In this case it was AirshipKit. Its hard to say why it was out of date, but it probably had to do with the different ways you were installing it through carthage and the manual installation methods.

Anyways, if you ever run into other build issues its usually good to try to clear the derived data as a first step. Especially after changing frameworks or build settings. `rm -rf ~/Library/Developer/Xcode/DerivedData/` is a sure fire way to clear it. I also hear Shift+Alt+Command+K will also clear it from within Xcode. 

Glad its fixed for you!

**Comment by LucasKovacs** [comment] 2017-07-28 21:34
thanks a lot for your help @rlepinski ! you help me a lot
