### ISSUE TITLE
'AirshipLib.h' file not found

### ISSUE THREAD

**Issue by mperovic** [urbanairship/ios-library#107] opened 2016-04-18 09:35 UTC
After updating to version 7.0.4 (pod update) I can't compile my project. Error is: 'AirshipLib.h' file not found.

**Comment by ecjs** [comment] 2016-04-21 21:49
Same.

**Comment by crow** [comment] 2016-04-21 22:07
Podfile contents as well as the cocoapods version used would be helpful to troubleshoot this. Thanks for bringing this to our attention.

**Comment by mperovic** [comment] 2016-04-22 08:39
This is podfile:
`source 'https://github.com/CocoaPods/Specs.git'

xcodeproj 'AskGamblers.xcodeproj'

target 'AskGamblers' do
	platform :ios, '8.0'
	use_frameworks!
	
	pod 'Alamofire', '~> 3.0'
	pod 'CCMPopup'
	pod 'SwiftyJSON', :git => 'https://github.com/SwiftyJSON/SwiftyJSON.git'
	pod 'GaugeKit'
	pod '1PasswordExtension'
	pod 'UrbanAirship-iOS-SDK'
	pod 'DeviceKit'
	pod 'Google/Analytics'
	pod 'Watchdog'
	pod 'KeychainAccess'
	pod 'Nuke'
	pod 'Nuke-Alamofire-Plugin'
	pod 'Nuke-AnimatedImage-Plugin'
	pod 'Preheat'
	pod 'DFCache'
	pod 'IQKeyboardManagerSwift', '~> 4.0'
end
`
cocoapods is v0.39.0 (latest stable version)

**Comment by crow** [comment] 2016-04-26 23:10
I am unable to produce this error with the podfile provided. 

My testing procedure:
- clone ua-ios-pod [(available here)](https://github.com/urbanairship/ua-ios-pod)
- edit the podfile in ua-ios-pod/PodSample to match podfile provided above (replacing 'MyProject' with 'PodSample')
- install and run PodSample project

Result:
The PodSample compiles and runs without errors. 

Is there any change in behavior when you explicitly set the version?
For example:
pod 'UrbanAirship-iOS-SDK' , '~> 7.0.4'

**Comment by GabrielCartier** [comment] 2016-05-25 20:58
Got the same exact problem with my project.
Specifying the version does not change anything.

**Comment by ajaybeniwal** [comment] 2016-08-19 09:21
+1 anyone looking into this issue

**Comment by rlepinski** [comment] 2016-08-19 17:12
We are unable to reproduce this locally. What import are you using for UA? `#import <AirshipKit/AirshipLib.h>` ?

**Comment by GabrielCartier** [comment] 2016-08-19 20:28
It started working again for us, not sure how we got to fix it.

**Comment by rlepinski** [comment] 2016-08-19 20:36
Did you update pod version or cocoapods?

**Comment by ajaybeniwal** [comment] 2016-08-20 02:10
pods --v 0.39.0 
#import <AirshipKit/AirshipKit.h>

**Comment by GabrielCartier** [comment] 2016-08-22 14:34
Didn't really follow up on the project, I can't seem to remember how we fixed it.

**Comment by rlepinski** [comment] 2016-08-22 16:12
@ajaybeniwal could you try with pods 1.0.0 (latest stable) and the latest UA pod?

**Comment by rlepinski** [comment] 2016-09-19 16:57
Closing until we get more info.

**Closed by rlepinski** 2016-09-19 16:57 UTC

**Comment by S0MMS** [comment] 2016-09-29 15:40
I am seeing this issue as well.  I've tried upgrading the UrbanAirship-iOS-SDK CocoaPod to both 7.0.4 and 8.0.4 from version 6.4.0 and get the same error above.  I'm running CocoaPods 1.0.1, XCode 8, Swift 2.3.  Any resolution?

**Comment by rlepinski** [comment] 2016-09-29 15:45
Could you double check you pod version? We do not have a 8.0.4 pod. Latest version is 8.0.1

**Comment by S0MMS** [comment] 2016-09-29 15:47
Sorry - my bad: I meant 8.0.1.

**Comment by rlepinski** [comment] 2016-09-29 16:27
@S0MMS how exactly are you importing the framework? import AirshipKit?

**Comment by erwinyu888** [comment] 2016-12-16 06:16
I am having the same problem, I cannot build my phonegap IOS project.  Saying AirshipLib.h not found.  Someone please help.

**Comment by astopo** [comment] 2017-02-01 21:39
I am trying to use this plugin with an Ionic2 project, seeing the same build error with XCode 8.2.1

**Comment by rlepinski** [comment] 2017-02-01 21:45
@erwinyu888 @astopo Please use https://github.com/urbanairship/phonegap-ua-push for any cordova issues. 

In cordova we now use cordova's cocoapod support. That requires you to use the generated xcworkspace instead of the xcproject. Give that a try. If that doesnt work please open a new issue and we can get more information.
