### ISSUE TITLE
UI API Called from Background Thread

### ISSUE THREAD

**Issue by raginggoat** [urbanairship/ios-library#139] opened 2017-07-20 19:12 UTC
On iOS 11 beta 3, I'm getting 

`/UAPush.m: runtime: UI API called from background thread: -[UIApplication backgroundRefreshStatus] must be called from main thread only`

on

```
#if !TARGET_OS_TV    // UIBackgroundRefreshStatusAvailable not available on tvOS
    if (app.backgroundRefreshStatus != UIBackgroundRefreshStatusAvailable) {
        return NO;
    }
```

and

`/UAPush.m: runtime: UI API called from background thread: -[UIApplication applicationIconBadgeNumber] must be called from main thread only`

on

`payload.badge = self.autobadgeEnabled ? [NSNumber numberWithInteger:[[UIApplication sharedApplication] applicationIconBadgeNumber]] : nil;`

**Comment by ralepinski** [comment] 2017-07-20 19:51
Thanks for the report. Will fix in the next patch release.

**Comment by rlepinski** [comment] 2017-07-20 19:52
Thanks for the report. Will fix in the next patch release.

**Comment by rlepinski** [comment] 2017-07-21 20:08
Fixed in 8.4.3

**Closed by rlepinski** 2017-07-21 20:08 UTC

**Comment by emablekos** [comment] 2017-08-14 14:51
Your solution is to dispatch sync on the main thread:
https://github.com/urbanairship/ios-library/commit/e6e175ac22d752e293de74ff90d84805e2f58958#diff-26d377b33ce49d2ee009967ddbbd5071R1105

Dispatch sync to the main thread seems likely to cause a thread lock.

You guys had a huge main thread lock happening in your release like one month ago, reported by several people.
https://github.com/urbanairship/ios-library/issues/137

Actually, its the previously closed issue.

**Comment by ralepinski** [comment] 2017-08-14 16:56
@emablekos Thanks for the feedback.

Issue #137 was caused by an overuse of a synchronize block in conjunction with a dispatch sync on the main queue.

We believe we do not have any more issues with our current SDK usage of that util method you listed. You are right that is does make it easier to introduce new deadlocks in the future and currently its possible for an app to cause a deadlock in an app if they dispatch_sync to a background thread and call a method that uses of that util method. Dispatch_syncs on the main queue is rare so we assume we are safe ATM but we are working on refactoring UAPush to remove that liability in the SDK.

**Comment by rlepinski** [comment] 2017-08-23 15:32
@emablekos Latest version removes all but 1 usage of dispatch_sync (still used in our analytics background queue).
