### ISSUE TITLE
After integrating AirshipKit, every Run triggers recompilation of all Swift files.

### ISSUE THREAD

**Issue by adityavyas** [urbanairship/ios-library#101] opened 2016-01-05 08:10 UTC
I'm using embedded framework approach for integrating Airship in my project. After integration every time I try to run my app (without cleaning) triggers entire project to recompile. So we are not able to leverage on incremental builds Xcode feature.

PS: Every run takes bizarre amount of time as I've lot of Swift files in my project.

**Comment by Anurag15990** [comment] 2016-01-06 08:36
+1

**Comment by rlepinski** [comment] 2016-01-06 23:34
Thanks for reporting this. We think we have identified the issue (the copy header script in the framework). We will report back once we have made more progress on the issue.

**Comment by marc-scig** [comment] 2016-01-06 23:54
Hey @adityavyas,

Sorry for the trouble. As incremental compilation wasn't available for early versions of Swift, we must have missed this when we first started working on AirshipKit. I think the recompilation is being caused by a bash script that AirshipKit runs to populate its list of internal headers. There should be a fix for this soon (SDK 7.0 will be coming out in the coming weeks) but in the meanwhile, as a workaround try replacing your AirshipKit/copy_header_imports.sh file with this modified version:

```
#!/bin/bash -ex

AIRSHIP_DIR="${SRCROOT}/../Airship"
FRAMEWORK_HEADERS_DIR="${BUILT_PRODUCTS_DIR}/AirshipKit.framework/Headers"
SOURCE_LIB_HEADER="${AIRSHIP_DIR}/AirshipLib.h"
TARGET_LIB_HEADER="${FRAMEWORK_HEADERS_DIR}/AirshipLib.h"

# if there's already an AirshipLib.h in the headers directory
if [ -a ${FRAMEWORK_HEADERS_DIR}/AirshipLib.h ]; then
    # if the contents haven't changed, exit early
    if diff -q "${SOURCE_LIB_HEADER}" "${TARGET_LIB_HEADER}" > /dev/null; then
        exit 0
    fi
fi

# Navigate to the public headers directory of the framework target and remove any existing headers

cd "$FRAMEWORK_HEADERS_DIR"
rm -rf *.h

# Find all public headers in the Airship directory, excluding UI
# Copy headers to the framework headers directory

cd "$AIRSHIP_DIR"
find . -type f -name '*.h' ! -name '*+Internal.h' ! -path './UI/*'\
  -exec cp {} "$FRAMEWORK_HEADERS_DIR/" \; \
```

**Comment by marc-scig** [comment] 2016-01-06 23:54
I think this should address what you're seeing, but let us know. Thanks for the feedback :)

**Comment by adityavyas** [comment] 2016-01-07 05:39
Hey @marc-scig, 

Thanks for the fix. It works! :)

**Closed** 2016-01-07 05:40 UTC
