### ISSUE TITLE
DeepLinkDelegate is missing the notification content

### ISSUE THREAD

**Issue by mmdumi** [urbanairship/ios-library#326] opened 2022-06-10 07:50 UTC
# Preliminary Info

### What Airship dependencies are you using?
Airship Core 16.7.0

### What are the versions of any relevant development tools you are using?
xcode 13.4 && iOS 15.5 

# Report

### What unexpected behavior are you seeing?
When our app is receiving a push notification with a deeplink action we get the `DeepLinkDelegate` protocol being triggered with `func receivedDeepLink(_ url: URL, completionHandler: @escaping () -> Void)` and this is the expected behaviour.
However this delegate doesn't contain any information about the notification that triggered this deeplink

### What is the expected behavior?
I would have expected for the `func receivedForegroundNotification` or `func receivedBackgroundNotification` or `func receivedNotificationResponse` to be called also in order to fetch the `notificationContent: [AnyHashable: Any]` details.
The reason I'm asking for the notification info is because in our app we need to send an app event with the notification details that triggered that deeplink

### What are the steps to reproduce the unexpected behavior?
Send a push notification with any deeplink as action from the airship web app.

**Comment by rlepinski** [comment] 2022-06-16 15:27
Many things can trigger a deep link, not just push. You should also receive a callback to receivedNotificationResponse. If that wont work for you, if you override the deep link action you can access the push through the action arguments metadata. That is a bit more complicated, so ideally you can just use receivedNotificationResponse

**Comment by mmdumi** [comment] 2022-06-20 10:31
Hi,
When the app is backgrounded:
- if the push contains the deeplink action - only the `receivedDeepLink` method gets triggered. Unfortunately `receivedNotificationResponse` does not get called. Maybe it's an issue in the latest version of the sdk ?
- if the push does NOT contain a deeplink action - `receivedNotificationResponse` get called as you suggested.

If the app is in foreground:
- `receivedForegroundNotification` and `receivedDeepLink` are called correctly

**Comment by Ulrico972** [comment] 2022-06-29 17:57
Hello @mmdumi,
I made some tests and the `receivedNotificationResponse` callback should be triggered even when the push contains a deeplink action.
However I think I reproduced your case with a tiny error in the `receivedDeepLink` method. If I forgot a completionHandler() call on a return for example, I got the same behavior as you.
Could you please send me your `receivedDeepLink` method so I could verify everything is alright ?

**Comment by rlepinski** [comment] 2022-07-01 00:53
Closing the issue since it seems resolved. Let me know if there is more to do on it

**Closed by rlepinski** 2022-07-01 00:53 UTC
